<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Preetams-MacBook-Air.local" failures="1" tests="5" name="com.tests.ValidationEpic1" time="25.696" errors="0" timestamp="2023-08-09T19:21:06 IST" skipped="4">
  <testcase classname="com.tests.ValidationEpic1" name="validateOfferesIsSelected2" time="15.258">
    <skipped/>
  </testcase> <!-- validateOfferesIsSelected2 -->
  <system-out/>
  <testcase classname="com.tests.ValidationEpic1" name="validateOfferesIsSelected2" time="10.438">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.pages.HomePage.negative(HomePage.java:73)
at com.tests.ValidationEpic1.validateOfferesIsSelected2(ValidationEpic1.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateOfferesIsSelected2 -->
  <system-out/>
  <testcase classname="com.tests.ValidationEpic1" name="validateHotelIsSelected">
    <skipped/>
  </testcase> <!-- validateHotelIsSelected -->
  <system-out/>
  <testcase classname="com.tests.ValidationEpic1" name="validateHotelIsSelected2">
    <skipped/>
  </testcase> <!-- validateHotelIsSelected2 -->
  <system-out/>
  <testcase classname="com.tests.ValidationEpic1" name="validateOfferesIsSelected">
    <skipped/>
  </testcase> <!-- validateOfferesIsSelected -->
  <system-out/>
</testsuite> <!-- com.tests.ValidationEpic1 -->
